# Generated by Django 5.2.4 on 2025-10-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='Minha Empresa', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('escuro', 'Escuro')], default='claro', max_length=20)),
                ('email_suporte', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone_suporte', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
